### ISSUE TITLE
New code hard to read / Maintain

### ISSUE THREAD

**Issue by kscholty** [digimer/Mermaids-Rest#19]
Hi,

I looked into the new STM32 code and found it hard to read and maintain.
There is a lot of common code copied for different cases.
I'd like to refactor it for you to make it better readable and maintainable, but that would cause so many conflicts with parallel changes.
If you like my help I propose to agree on a period of let's say 1-2 Days where you don't do any changes so that we don't get too many conflicts.

As it is now you will have a very hard time not to break one of the different if branches by changing only one or two.
Just let me knwo whether or not you would like my help with that.

**Comment by PurpleAlien** [comment]
Agreed. Like I mentioned in the other suggestion I opened, one could start with getting rid of all those individual variables and group them in structs. Next, I would migrate all the control code out of main and move it into separate files. That way maintainability and just general modification/contributions will become so much easier...

**Comment by digimer** [comment]
Howdy! I'm actually travelling on work until Tuesday (next week). So if you'd like to have a go at it, I'd appreciate it. My only real request is that you add comments so I can follow along / understand the changes. :) I think this might be a great chance for me to learn some better practices!

**Comment by digimer** [comment]
Closing this issue now that PR 21 has merged. :)
