### ISSUE TITLE
Output display incorrect when main switch is off

### ISSUE THREAD

**Issue by schoppert** [digimer/Mermaids-Rest#2]
Just a minor suggestion to help get past the output display issue when the main switch is off.

The idea is to only read the sensor when the switch is on ... otherwise, just set the sensor value to something in the neutral range.  That way, the code to do the print out and set the dac value is the same in both cases ( which reduces testing ).

Something like this:

```
  int32_t sensorValue;
  if (mainSwitchVal == 0) {
    // Switch is off, force the sensorValue to the middle of the nuetral range
    sensorValue = (reverseMinimum + forwardMinimum)/2;
  } else {
    // only read the sensor value if the main switch is on
    sensorValue = analogRead(A0);
  }

  //** Proceed to the sensor evaluation code 

  if ((sensorValue >= reverseMaximum) && (sensorValue <= reverseMinimum))
```

Not sure if you want outside input, but figured I would try to help with a simple fix to a simple issue ... no need to increase complexity if you don't have to.  Good luck on the project!

**Comment by digimer** [comment]
Oh, I like this approach! I absolutely want outside help, so this is appreciated! Could I trouble you to create a PR? No worries if not, I can also, though you creating a PR would let me credit the contribution directly in the git logs. I can test your version this evening. :)

**Comment by schoppert** [comment]
Sure, was resisting opening an official PR simply because I couldn't actually test the change.  But, if that makes it easier for you I will go that route.

**Comment by digimer** [comment]
I'll load your version when I'm next on the bench and see if it works. If so, then I'll merge. Thanks!!
